version: "3.2"
services:
  antibruteforce-service:
    container_name: antibruteforce-grpc-server
    build:
      context: .
      dockerfile: Dockerfile
    image: antibruteforce-server
    ports:
      - "8080"
    environment:
      METRICS_PORT: "9001"
      GRPC-SRV-HOST: "0.0.0.0"
      GRPC-SRV-PORT: "8080"
      IP-LIMIT: "100"
      PASSWORD-LIMIT: "50"
      DSN: "antibruteforce_configdb.bbolt"
      STORAGE: "bolt"
    command: "/app/server"
    restart: on-failure

  integration_tests:
      image: antibruteforce-integration-tests
      build:
        context: .
        dockerfile: Dockerfile-test
      command: make integration-tests
      depends_on:
        - antibruteforce-service

