version: "3.2"
services:
  antibruteforce-service:
    container_name: antibruteforce-grpc-server
    build:
      context: .
      dockerfile: Dockerfile
    image: antibruteforce-server
    ports:
      - "8080:8080"
      - "9001:9001"
    environment:
      METRICS_PORT: "9001"
      GRPC-SRV-HOST: "0.0.0.0"
      GRPC-SRV-PORT: "8080"
      DSN: ""
      STORAGE: "map"
      VERBOSE: "true"
    command: "/app/server"
    restart: on-failure

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: --config.file=/etc/prometheus/prometheus.yml
