// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Auth struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Ip                   string   `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Auth) Reset()         { *m = Auth{} }
func (m *Auth) String() string { return proto.CompactTextString(m) }
func (*Auth) ProtoMessage()    {}
func (*Auth) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{0}
}

func (m *Auth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth.Unmarshal(m, b)
}
func (m *Auth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth.Marshal(b, m, deterministic)
}
func (m *Auth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth.Merge(m, src)
}
func (m *Auth) XXX_Size() int {
	return xxx_messageInfo_Auth.Size(m)
}
func (m *Auth) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth.DiscardUnknown(m)
}

var xxx_messageInfo_Auth proto.InternalMessageInfo

func (m *Auth) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *Auth) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Auth) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type CheckAuthRequest struct {
	Auth                 *Auth    `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckAuthRequest) Reset()         { *m = CheckAuthRequest{} }
func (m *CheckAuthRequest) String() string { return proto.CompactTextString(m) }
func (*CheckAuthRequest) ProtoMessage()    {}
func (*CheckAuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{1}
}

func (m *CheckAuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckAuthRequest.Unmarshal(m, b)
}
func (m *CheckAuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckAuthRequest.Marshal(b, m, deterministic)
}
func (m *CheckAuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckAuthRequest.Merge(m, src)
}
func (m *CheckAuthRequest) XXX_Size() int {
	return xxx_messageInfo_CheckAuthRequest.Size(m)
}
func (m *CheckAuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckAuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckAuthRequest proto.InternalMessageInfo

func (m *CheckAuthRequest) GetAuth() *Auth {
	if m != nil {
		return m.Auth
	}
	return nil
}

type CheckAuthResponse struct {
	// Types that are valid to be assigned to Result:
	//	*CheckAuthResponse_Ok
	//	*CheckAuthResponse_Error
	Result               isCheckAuthResponse_Result `protobuf_oneof:"result"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *CheckAuthResponse) Reset()         { *m = CheckAuthResponse{} }
func (m *CheckAuthResponse) String() string { return proto.CompactTextString(m) }
func (*CheckAuthResponse) ProtoMessage()    {}
func (*CheckAuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{2}
}

func (m *CheckAuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckAuthResponse.Unmarshal(m, b)
}
func (m *CheckAuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckAuthResponse.Marshal(b, m, deterministic)
}
func (m *CheckAuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckAuthResponse.Merge(m, src)
}
func (m *CheckAuthResponse) XXX_Size() int {
	return xxx_messageInfo_CheckAuthResponse.Size(m)
}
func (m *CheckAuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckAuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckAuthResponse proto.InternalMessageInfo

type isCheckAuthResponse_Result interface {
	isCheckAuthResponse_Result()
}

type CheckAuthResponse_Ok struct {
	Ok bool `protobuf:"varint,1,opt,name=ok,proto3,oneof"`
}

type CheckAuthResponse_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*CheckAuthResponse_Ok) isCheckAuthResponse_Result() {}

func (*CheckAuthResponse_Error) isCheckAuthResponse_Result() {}

func (m *CheckAuthResponse) GetResult() isCheckAuthResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *CheckAuthResponse) GetOk() bool {
	if x, ok := m.GetResult().(*CheckAuthResponse_Ok); ok {
		return x.Ok
	}
	return false
}

func (m *CheckAuthResponse) GetError() string {
	if x, ok := m.GetResult().(*CheckAuthResponse_Error); ok {
		return x.Error
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*CheckAuthResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*CheckAuthResponse_Ok)(nil),
		(*CheckAuthResponse_Error)(nil),
	}
}

type AddToWhiteListRequest struct {
	Net                  string   `protobuf:"bytes,1,opt,name=net,proto3" json:"net,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddToWhiteListRequest) Reset()         { *m = AddToWhiteListRequest{} }
func (m *AddToWhiteListRequest) String() string { return proto.CompactTextString(m) }
func (*AddToWhiteListRequest) ProtoMessage()    {}
func (*AddToWhiteListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{3}
}

func (m *AddToWhiteListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddToWhiteListRequest.Unmarshal(m, b)
}
func (m *AddToWhiteListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddToWhiteListRequest.Marshal(b, m, deterministic)
}
func (m *AddToWhiteListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddToWhiteListRequest.Merge(m, src)
}
func (m *AddToWhiteListRequest) XXX_Size() int {
	return xxx_messageInfo_AddToWhiteListRequest.Size(m)
}
func (m *AddToWhiteListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddToWhiteListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddToWhiteListRequest proto.InternalMessageInfo

func (m *AddToWhiteListRequest) GetNet() string {
	if m != nil {
		return m.Net
	}
	return ""
}

type AddToWhiteListResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddToWhiteListResponse) Reset()         { *m = AddToWhiteListResponse{} }
func (m *AddToWhiteListResponse) String() string { return proto.CompactTextString(m) }
func (*AddToWhiteListResponse) ProtoMessage()    {}
func (*AddToWhiteListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{4}
}

func (m *AddToWhiteListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddToWhiteListResponse.Unmarshal(m, b)
}
func (m *AddToWhiteListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddToWhiteListResponse.Marshal(b, m, deterministic)
}
func (m *AddToWhiteListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddToWhiteListResponse.Merge(m, src)
}
func (m *AddToWhiteListResponse) XXX_Size() int {
	return xxx_messageInfo_AddToWhiteListResponse.Size(m)
}
func (m *AddToWhiteListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddToWhiteListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddToWhiteListResponse proto.InternalMessageInfo

func (m *AddToWhiteListResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type AddToBlackListRequest struct {
	Net                  string   `protobuf:"bytes,1,opt,name=net,proto3" json:"net,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddToBlackListRequest) Reset()         { *m = AddToBlackListRequest{} }
func (m *AddToBlackListRequest) String() string { return proto.CompactTextString(m) }
func (*AddToBlackListRequest) ProtoMessage()    {}
func (*AddToBlackListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{5}
}

func (m *AddToBlackListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddToBlackListRequest.Unmarshal(m, b)
}
func (m *AddToBlackListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddToBlackListRequest.Marshal(b, m, deterministic)
}
func (m *AddToBlackListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddToBlackListRequest.Merge(m, src)
}
func (m *AddToBlackListRequest) XXX_Size() int {
	return xxx_messageInfo_AddToBlackListRequest.Size(m)
}
func (m *AddToBlackListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddToBlackListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddToBlackListRequest proto.InternalMessageInfo

func (m *AddToBlackListRequest) GetNet() string {
	if m != nil {
		return m.Net
	}
	return ""
}

type AddToBlackListResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddToBlackListResponse) Reset()         { *m = AddToBlackListResponse{} }
func (m *AddToBlackListResponse) String() string { return proto.CompactTextString(m) }
func (*AddToBlackListResponse) ProtoMessage()    {}
func (*AddToBlackListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{6}
}

func (m *AddToBlackListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddToBlackListResponse.Unmarshal(m, b)
}
func (m *AddToBlackListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddToBlackListResponse.Marshal(b, m, deterministic)
}
func (m *AddToBlackListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddToBlackListResponse.Merge(m, src)
}
func (m *AddToBlackListResponse) XXX_Size() int {
	return xxx_messageInfo_AddToBlackListResponse.Size(m)
}
func (m *AddToBlackListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddToBlackListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddToBlackListResponse proto.InternalMessageInfo

func (m *AddToBlackListResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type DeleteFromWhiteListRequest struct {
	Net                  string   `protobuf:"bytes,1,opt,name=net,proto3" json:"net,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFromWhiteListRequest) Reset()         { *m = DeleteFromWhiteListRequest{} }
func (m *DeleteFromWhiteListRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteFromWhiteListRequest) ProtoMessage()    {}
func (*DeleteFromWhiteListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{7}
}

func (m *DeleteFromWhiteListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFromWhiteListRequest.Unmarshal(m, b)
}
func (m *DeleteFromWhiteListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFromWhiteListRequest.Marshal(b, m, deterministic)
}
func (m *DeleteFromWhiteListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFromWhiteListRequest.Merge(m, src)
}
func (m *DeleteFromWhiteListRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteFromWhiteListRequest.Size(m)
}
func (m *DeleteFromWhiteListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFromWhiteListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFromWhiteListRequest proto.InternalMessageInfo

func (m *DeleteFromWhiteListRequest) GetNet() string {
	if m != nil {
		return m.Net
	}
	return ""
}

type DeleteFromWhiteListResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFromWhiteListResponse) Reset()         { *m = DeleteFromWhiteListResponse{} }
func (m *DeleteFromWhiteListResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteFromWhiteListResponse) ProtoMessage()    {}
func (*DeleteFromWhiteListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{8}
}

func (m *DeleteFromWhiteListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFromWhiteListResponse.Unmarshal(m, b)
}
func (m *DeleteFromWhiteListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFromWhiteListResponse.Marshal(b, m, deterministic)
}
func (m *DeleteFromWhiteListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFromWhiteListResponse.Merge(m, src)
}
func (m *DeleteFromWhiteListResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteFromWhiteListResponse.Size(m)
}
func (m *DeleteFromWhiteListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFromWhiteListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFromWhiteListResponse proto.InternalMessageInfo

func (m *DeleteFromWhiteListResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type DeleteFromBlackListRequest struct {
	Net                  string   `protobuf:"bytes,1,opt,name=net,proto3" json:"net,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFromBlackListRequest) Reset()         { *m = DeleteFromBlackListRequest{} }
func (m *DeleteFromBlackListRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteFromBlackListRequest) ProtoMessage()    {}
func (*DeleteFromBlackListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{9}
}

func (m *DeleteFromBlackListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFromBlackListRequest.Unmarshal(m, b)
}
func (m *DeleteFromBlackListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFromBlackListRequest.Marshal(b, m, deterministic)
}
func (m *DeleteFromBlackListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFromBlackListRequest.Merge(m, src)
}
func (m *DeleteFromBlackListRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteFromBlackListRequest.Size(m)
}
func (m *DeleteFromBlackListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFromBlackListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFromBlackListRequest proto.InternalMessageInfo

func (m *DeleteFromBlackListRequest) GetNet() string {
	if m != nil {
		return m.Net
	}
	return ""
}

type DeleteFromBlackListResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFromBlackListResponse) Reset()         { *m = DeleteFromBlackListResponse{} }
func (m *DeleteFromBlackListResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteFromBlackListResponse) ProtoMessage()    {}
func (*DeleteFromBlackListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{10}
}

func (m *DeleteFromBlackListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFromBlackListResponse.Unmarshal(m, b)
}
func (m *DeleteFromBlackListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFromBlackListResponse.Marshal(b, m, deterministic)
}
func (m *DeleteFromBlackListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFromBlackListResponse.Merge(m, src)
}
func (m *DeleteFromBlackListResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteFromBlackListResponse.Size(m)
}
func (m *DeleteFromBlackListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFromBlackListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFromBlackListResponse proto.InternalMessageInfo

func (m *DeleteFromBlackListResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ResetLimitRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Ip                   string   `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetLimitRequest) Reset()         { *m = ResetLimitRequest{} }
func (m *ResetLimitRequest) String() string { return proto.CompactTextString(m) }
func (*ResetLimitRequest) ProtoMessage()    {}
func (*ResetLimitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{11}
}

func (m *ResetLimitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetLimitRequest.Unmarshal(m, b)
}
func (m *ResetLimitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetLimitRequest.Marshal(b, m, deterministic)
}
func (m *ResetLimitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetLimitRequest.Merge(m, src)
}
func (m *ResetLimitRequest) XXX_Size() int {
	return xxx_messageInfo_ResetLimitRequest.Size(m)
}
func (m *ResetLimitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetLimitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetLimitRequest proto.InternalMessageInfo

func (m *ResetLimitRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *ResetLimitRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type ResetLimitResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetLimitResponse) Reset()         { *m = ResetLimitResponse{} }
func (m *ResetLimitResponse) String() string { return proto.CompactTextString(m) }
func (*ResetLimitResponse) ProtoMessage()    {}
func (*ResetLimitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{12}
}

func (m *ResetLimitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetLimitResponse.Unmarshal(m, b)
}
func (m *ResetLimitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetLimitResponse.Marshal(b, m, deterministic)
}
func (m *ResetLimitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetLimitResponse.Merge(m, src)
}
func (m *ResetLimitResponse) XXX_Size() int {
	return xxx_messageInfo_ResetLimitResponse.Size(m)
}
func (m *ResetLimitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetLimitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResetLimitResponse proto.InternalMessageInfo

func (m *ResetLimitResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*Auth)(nil), "Auth")
	proto.RegisterType((*CheckAuthRequest)(nil), "CheckAuthRequest")
	proto.RegisterType((*CheckAuthResponse)(nil), "CheckAuthResponse")
	proto.RegisterType((*AddToWhiteListRequest)(nil), "AddToWhiteListRequest")
	proto.RegisterType((*AddToWhiteListResponse)(nil), "AddToWhiteListResponse")
	proto.RegisterType((*AddToBlackListRequest)(nil), "AddToBlackListRequest")
	proto.RegisterType((*AddToBlackListResponse)(nil), "AddToBlackListResponse")
	proto.RegisterType((*DeleteFromWhiteListRequest)(nil), "DeleteFromWhiteListRequest")
	proto.RegisterType((*DeleteFromWhiteListResponse)(nil), "DeleteFromWhiteListResponse")
	proto.RegisterType((*DeleteFromBlackListRequest)(nil), "DeleteFromBlackListRequest")
	proto.RegisterType((*DeleteFromBlackListResponse)(nil), "DeleteFromBlackListResponse")
	proto.RegisterType((*ResetLimitRequest)(nil), "ResetLimitRequest")
	proto.RegisterType((*ResetLimitResponse)(nil), "ResetLimitResponse")
}

func init() { proto.RegisterFile("api/api.proto", fileDescriptor_1b40cafcd4234784) }

var fileDescriptor_1b40cafcd4234784 = []byte{
	// 415 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x5d, 0xa7, 0xa9, 0xd2, 0x41, 0x54, 0xc9, 0xb4, 0x0d, 0xc1, 0xed, 0x01, 0xed, 0x09,
	0x90, 0x58, 0xa4, 0x16, 0x09, 0x71, 0x4c, 0x8a, 0x4a, 0x0e, 0x3d, 0x19, 0x24, 0xce, 0xc6, 0x19,
	0xe1, 0x95, 0x1d, 0xaf, 0xd9, 0x5d, 0xc3, 0xab, 0xf1, 0x78, 0x28, 0xeb, 0xd8, 0x71, 0x6c, 0x63,
	0xf9, 0xe6, 0xd9, 0x1d, 0x7f, 0xdf, 0xfc, 0xf9, 0x69, 0xe1, 0x79, 0x90, 0x89, 0xf7, 0x41, 0x26,
	0x78, 0xa6, 0xa4, 0x91, 0x6c, 0x0d, 0xa7, 0xcb, 0xdc, 0x44, 0x78, 0x05, 0xe3, 0x44, 0xfe, 0x14,
	0xe9, 0xe2, 0xe4, 0xd5, 0xc9, 0xeb, 0x73, 0xbf, 0x08, 0xd0, 0x83, 0x49, 0x16, 0x68, 0xfd, 0x47,
	0xaa, 0xcd, 0xc2, 0xb5, 0x17, 0x55, 0x8c, 0x17, 0xe0, 0x8a, 0x6c, 0x31, 0xb2, 0xa7, 0xae, 0xc8,
	0xd8, 0x3b, 0x98, 0x3e, 0x44, 0x14, 0xc6, 0x3b, 0x39, 0x9f, 0x7e, 0xe5, 0xa4, 0x0d, 0xbe, 0x84,
	0xd3, 0x20, 0x37, 0x91, 0x15, 0x7d, 0x76, 0x37, 0xe6, 0xf6, 0xce, 0x1e, 0xb1, 0x2f, 0x30, 0xab,
	0xa5, 0xeb, 0x4c, 0xa6, 0x9a, 0x70, 0x0a, 0xae, 0x8c, 0x6d, 0xf6, 0x64, 0xed, 0xf8, 0xae, 0x8c,
	0x71, 0x0e, 0x63, 0x52, 0x4a, 0xaa, 0xc2, 0x7e, 0xed, 0xf8, 0x45, 0xb8, 0x9a, 0xc0, 0x99, 0x22,
	0x9d, 0x27, 0x86, 0xbd, 0x81, 0xeb, 0xe5, 0x66, 0xf3, 0x4d, 0x7e, 0x8f, 0x84, 0xa1, 0x27, 0xa1,
	0x4d, 0x69, 0x3e, 0x85, 0x51, 0x4a, 0x66, 0xdf, 0xd0, 0xee, 0x93, 0x71, 0x98, 0x37, 0x53, 0xf7,
	0xc6, 0x57, 0xa5, 0xcd, 0xbe, 0x7d, 0x1b, 0x54, 0xd2, 0xab, 0x24, 0x08, 0xe3, 0x61, 0xd2, 0xb5,
	0xd4, 0x5e, 0x69, 0x0e, 0xde, 0x67, 0x4a, 0xc8, 0xd0, 0xa3, 0x92, 0xdb, 0x01, 0xa5, 0xdf, 0xc3,
	0x4d, 0x67, 0xfe, 0x70, 0x93, 0x01, 0x4d, 0x1c, 0x99, 0x0c, 0xed, 0xe4, 0x13, 0xcc, 0x7c, 0xd2,
	0x64, 0x9e, 0xc4, 0x56, 0x54, 0xda, 0xdd, 0x38, 0x15, 0xc8, 0xb8, 0x15, 0x32, 0x6f, 0x01, 0xeb,
	0xbf, 0xf6, 0xd9, 0xdc, 0xfd, 0x1d, 0xc1, 0xf5, 0x32, 0x35, 0x62, 0xa5, 0x72, 0x43, 0x8f, 0x52,
	0x85, 0xf4, 0x95, 0xd4, 0x6f, 0x11, 0x12, 0x7e, 0x80, 0xf3, 0x8a, 0x24, 0x9c, 0xf1, 0x26, 0x84,
	0x1e, 0xf2, 0x16, 0x68, 0xcc, 0xc1, 0x07, 0xb8, 0x38, 0x66, 0x01, 0xe7, 0xbc, 0x93, 0x23, 0xef,
	0x05, 0xef, 0x86, 0xa6, 0x26, 0x52, 0xcd, 0xaa, 0x14, 0x69, 0x0e, 0xbb, 0x14, 0x69, 0x0d, 0x95,
	0x39, 0xe8, 0xc3, 0x65, 0xc7, 0x6a, 0xf1, 0x86, 0xff, 0x1f, 0x10, 0xef, 0x96, 0xf7, 0xd0, 0xd0,
	0xd4, 0x3c, 0x54, 0x57, 0xd7, 0x6c, 0x95, 0x78, 0xcb, 0x7b, 0x96, 0xcf, 0x1c, 0xfc, 0x08, 0x70,
	0xd8, 0x16, 0x22, 0x6f, 0x6d, 0xdd, 0xbb, 0xe4, 0xed, 0x75, 0x32, 0xe7, 0xc7, 0x99, 0x7d, 0x6a,
	0xee, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0x57, 0x6c, 0x9b, 0xbb, 0x7b, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AntiBruteForceServiceClient is the client API for AntiBruteForceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AntiBruteForceServiceClient interface {
	CheckAuth(ctx context.Context, in *CheckAuthRequest, opts ...grpc.CallOption) (*CheckAuthResponse, error)
	AddToWhiteList(ctx context.Context, in *AddToWhiteListRequest, opts ...grpc.CallOption) (*AddToWhiteListResponse, error)
	AddToBlackList(ctx context.Context, in *AddToBlackListRequest, opts ...grpc.CallOption) (*AddToBlackListResponse, error)
	DeleteFromWhiteList(ctx context.Context, in *DeleteFromWhiteListRequest, opts ...grpc.CallOption) (*DeleteFromWhiteListResponse, error)
	DeleteFromBlackList(ctx context.Context, in *DeleteFromBlackListRequest, opts ...grpc.CallOption) (*DeleteFromBlackListResponse, error)
	ResetLimit(ctx context.Context, in *ResetLimitRequest, opts ...grpc.CallOption) (*ResetLimitResponse, error)
}

type antiBruteForceServiceClient struct {
	cc *grpc.ClientConn
}

func NewAntiBruteForceServiceClient(cc *grpc.ClientConn) AntiBruteForceServiceClient {
	return &antiBruteForceServiceClient{cc}
}

func (c *antiBruteForceServiceClient) CheckAuth(ctx context.Context, in *CheckAuthRequest, opts ...grpc.CallOption) (*CheckAuthResponse, error) {
	out := new(CheckAuthResponse)
	err := c.cc.Invoke(ctx, "/AntiBruteForceService/CheckAuth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *antiBruteForceServiceClient) AddToWhiteList(ctx context.Context, in *AddToWhiteListRequest, opts ...grpc.CallOption) (*AddToWhiteListResponse, error) {
	out := new(AddToWhiteListResponse)
	err := c.cc.Invoke(ctx, "/AntiBruteForceService/AddToWhiteList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *antiBruteForceServiceClient) AddToBlackList(ctx context.Context, in *AddToBlackListRequest, opts ...grpc.CallOption) (*AddToBlackListResponse, error) {
	out := new(AddToBlackListResponse)
	err := c.cc.Invoke(ctx, "/AntiBruteForceService/AddToBlackList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *antiBruteForceServiceClient) DeleteFromWhiteList(ctx context.Context, in *DeleteFromWhiteListRequest, opts ...grpc.CallOption) (*DeleteFromWhiteListResponse, error) {
	out := new(DeleteFromWhiteListResponse)
	err := c.cc.Invoke(ctx, "/AntiBruteForceService/DeleteFromWhiteList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *antiBruteForceServiceClient) DeleteFromBlackList(ctx context.Context, in *DeleteFromBlackListRequest, opts ...grpc.CallOption) (*DeleteFromBlackListResponse, error) {
	out := new(DeleteFromBlackListResponse)
	err := c.cc.Invoke(ctx, "/AntiBruteForceService/DeleteFromBlackList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *antiBruteForceServiceClient) ResetLimit(ctx context.Context, in *ResetLimitRequest, opts ...grpc.CallOption) (*ResetLimitResponse, error) {
	out := new(ResetLimitResponse)
	err := c.cc.Invoke(ctx, "/AntiBruteForceService/ResetLimit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AntiBruteForceServiceServer is the server API for AntiBruteForceService service.
type AntiBruteForceServiceServer interface {
	CheckAuth(context.Context, *CheckAuthRequest) (*CheckAuthResponse, error)
	AddToWhiteList(context.Context, *AddToWhiteListRequest) (*AddToWhiteListResponse, error)
	AddToBlackList(context.Context, *AddToBlackListRequest) (*AddToBlackListResponse, error)
	DeleteFromWhiteList(context.Context, *DeleteFromWhiteListRequest) (*DeleteFromWhiteListResponse, error)
	DeleteFromBlackList(context.Context, *DeleteFromBlackListRequest) (*DeleteFromBlackListResponse, error)
	ResetLimit(context.Context, *ResetLimitRequest) (*ResetLimitResponse, error)
}

// UnimplementedAntiBruteForceServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAntiBruteForceServiceServer struct {
}

func (*UnimplementedAntiBruteForceServiceServer) CheckAuth(ctx context.Context, req *CheckAuthRequest) (*CheckAuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckAuth not implemented")
}
func (*UnimplementedAntiBruteForceServiceServer) AddToWhiteList(ctx context.Context, req *AddToWhiteListRequest) (*AddToWhiteListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddToWhiteList not implemented")
}
func (*UnimplementedAntiBruteForceServiceServer) AddToBlackList(ctx context.Context, req *AddToBlackListRequest) (*AddToBlackListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddToBlackList not implemented")
}
func (*UnimplementedAntiBruteForceServiceServer) DeleteFromWhiteList(ctx context.Context, req *DeleteFromWhiteListRequest) (*DeleteFromWhiteListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFromWhiteList not implemented")
}
func (*UnimplementedAntiBruteForceServiceServer) DeleteFromBlackList(ctx context.Context, req *DeleteFromBlackListRequest) (*DeleteFromBlackListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFromBlackList not implemented")
}
func (*UnimplementedAntiBruteForceServiceServer) ResetLimit(ctx context.Context, req *ResetLimitRequest) (*ResetLimitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetLimit not implemented")
}

func RegisterAntiBruteForceServiceServer(s *grpc.Server, srv AntiBruteForceServiceServer) {
	s.RegisterService(&_AntiBruteForceService_serviceDesc, srv)
}

func _AntiBruteForceService_CheckAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiBruteForceServiceServer).CheckAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AntiBruteForceService/CheckAuth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiBruteForceServiceServer).CheckAuth(ctx, req.(*CheckAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AntiBruteForceService_AddToWhiteList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddToWhiteListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiBruteForceServiceServer).AddToWhiteList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AntiBruteForceService/AddToWhiteList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiBruteForceServiceServer).AddToWhiteList(ctx, req.(*AddToWhiteListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AntiBruteForceService_AddToBlackList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddToBlackListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiBruteForceServiceServer).AddToBlackList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AntiBruteForceService/AddToBlackList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiBruteForceServiceServer).AddToBlackList(ctx, req.(*AddToBlackListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AntiBruteForceService_DeleteFromWhiteList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFromWhiteListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiBruteForceServiceServer).DeleteFromWhiteList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AntiBruteForceService/DeleteFromWhiteList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiBruteForceServiceServer).DeleteFromWhiteList(ctx, req.(*DeleteFromWhiteListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AntiBruteForceService_DeleteFromBlackList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFromBlackListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiBruteForceServiceServer).DeleteFromBlackList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AntiBruteForceService/DeleteFromBlackList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiBruteForceServiceServer).DeleteFromBlackList(ctx, req.(*DeleteFromBlackListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AntiBruteForceService_ResetLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiBruteForceServiceServer).ResetLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AntiBruteForceService/ResetLimit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiBruteForceServiceServer).ResetLimit(ctx, req.(*ResetLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AntiBruteForceService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "AntiBruteForceService",
	HandlerType: (*AntiBruteForceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckAuth",
			Handler:    _AntiBruteForceService_CheckAuth_Handler,
		},
		{
			MethodName: "AddToWhiteList",
			Handler:    _AntiBruteForceService_AddToWhiteList_Handler,
		},
		{
			MethodName: "AddToBlackList",
			Handler:    _AntiBruteForceService_AddToBlackList_Handler,
		},
		{
			MethodName: "DeleteFromWhiteList",
			Handler:    _AntiBruteForceService_DeleteFromWhiteList_Handler,
		},
		{
			MethodName: "DeleteFromBlackList",
			Handler:    _AntiBruteForceService_DeleteFromBlackList_Handler,
		},
		{
			MethodName: "ResetLimit",
			Handler:    _AntiBruteForceService_ResetLimit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/api.proto",
}
